FROM alpine/java:17-jdk

WORKDIR /app

RUN addgroup --gid 1000 appuser && \
    adduser --disabled-password \
    --gecos "" \
    --ingroup appuser \
    --no-create-time \
    --uid 1000 \
    akash
 
COPY --chown=1000:1000 ../target/Crud-0.0.1-SNAPSHOT.jar .
USER 1000
ENTRYPOINT ["java", "-jar", "Crud-0.0.1-SNAPSHOT.jar"]
