FROM alpine/java:17-jdk

WORKDIR /app

RUN addgroup -g 1000 appuser && \
    adduser -D -u 1000 -G appuser akash
 
COPY --chown=1000:1000 ../target/Crud-0.0.1-SNAPSHOT.jar .

USER 1000

ENTRYPOINT ["java", "-jar", "Crud-0.0.1-SNAPSHOT.jar"]
